### ISSUE TITLE
Player Point Bug

### ISSUE THREAD

**Issue by codingTD-web** [Klemms/SlotMachineIssues#15]
Hello,I was Download the Slot machine Plugin into My Minecraft Server.I also Install the Player Point Plugin For The Slot machine,Everything is Fine Before the 6.3.4 Update.But,When I Update the Plugin Version to 6.3.4,i can't ser the slot machine to using the player point system.Althought,I was restart and reinstall the plugin,it still can't work.Can you fixed this Bug as soon as possible?Due My Server have some Player is Waiting me to public the player points system and slot machine update.Thank You

**Comment by codingTD-web** [comment]
P.S Before 6.3.4, It can make the Machine to Use the Player Point Plugin
After I Install the 6.3..4 Version, All Slot Machine using Player Point System were broken

**Comment by Klemms** [comment]
PlayerPoints support has been dropped as of 6.3.3. This was specified in patch notes [https://www.spigotmc.org/resources/slot-machine.22023/update?update=392333](https://www.spigotmc.org/resources/slot-machine.22023/update?update=392333)

You can use GamePoints as an alternative [https://www.spigotmc.org/resources/gamepoints-%E2%80%A2-additional-custom-currency-1-14-1-16.84121/](https://www.spigotmc.org/resources/gamepoints-%E2%80%A2-additional-custom-currency-1-14-1-16.84121/)
