### ISSUE TITLE
You can press F to duplicate the item in Slot Machine GUI

### ISSUE THREAD

**Issue by notynote** [Klemms/SlotMachineIssues#17]
It will copy that Item to off-hand

**Comment by Kbryst** [comment]
When I close out the slot machine gui and move, it goes away. Can you add more info to your issue and how to recreate it?

**Comment by notynote** [comment]
I just test again, and it appears that it is going to happen only when you in a Creative Gamemode.

I think it wouldn't affect normal player now. Sorry for a misleading information.

**Comment by Klemms** [comment]
This is only a visual bug, I'd rather not change the UI code as I'm not the developer of the library i'm using for UIs
