### ISSUE TITLE
[1.16.5] [Mohist] Error console

### ISSUE THREAD

**Issue by DaDiGui** [Klemms/SlotMachineIssues#19]
mohist-1.16.5-678-server
https://pastebin.com/Ryzcfhdr
I get this error in console but the plugin works correctly.

**Comment by Klemms** [comment]
This is hapenning because I compiled the latest version of SlotMachine against Java 16, the next release will probably be compiled with java 8. However you should upgrade to Java 16 as anyway, Minecraft 1.17 requires Java 16

**Comment by DaDiGui** [comment]
Even if I don't use 1.17, should I upgrade to Java16? I am currently on 1.16.5

**Comment by Klemms** [comment]
The latest version has been re-compiled with Java 8 to work with old minecraft version for the moment
