### ISSUE TITLE
Add option to disable AutoUpdate

### ISSUE THREAD

**Issue by piotrskibapl** [Klemms/SlotMachineIssues#2]
Hello,

It would be great if you add an option to disable AutoUpdate for this plugin. Sometimes Minecraft hosting providers or server administrators doesn't allow to make connections to any external services, for example, due to security reasons. I'm an administrator of a Minecraft server, and I have to disable AutoUpdate for almost every plugin on the server. Not doing so may lead to a crash - as with SlotMachine. Because of that, I can't actually have SlotMachine installed on my server.

Attaching some logs: https://pastebin.com/RueEJWbB

**Comment by Klemms** [comment]
Hi,

This is already implemented, check the "KlemmsUpdate" folder of your plugins folder
