### ISSUE TITLE
Error spammed in the console

### ISSUE THREAD

**Issue by NicoNekoDev** [Klemms/SlotMachineIssues#23]
https://paste.md-5.net/kavezocewe.sql
https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerInteractEvent.html#getHand() -> it can be null

Looking at the error it looks like a player has stepped on a redstone ore block and triggered the PlayerInteractEvent with the action [`PHYSICAL`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/Action.html#PHYSICAL)

**Comment by Klemms** [comment]
Fixed it in 6.5.4 was just 2 conditions in the wrong order

from this `if (event.getHand().equals(EquipmentSlot.HAND) && event.getAction() == Action.RIGHT_CLICK_BLOCK)`
to this `if (event.getAction() == Action.RIGHT_CLICK_BLOCK && event.getHand().equals(EquipmentSlot.HAND))`
