### ISSUE TITLE
Add support for MyWorlds

### ISSUE THREAD

**Issue by NicoNekoDev** [Klemms/SlotMachineIssues#24]
`15.01 10:24:35 [Server] ERROR A Slot Machine Entity (9edf7740-b438-4b50-b05b-e5b68f322c8b) coudln't be found on its original chunk, this Slot Machine has been loaded but may not work correctly. If you use a different plugin than Multiverse-Core or MultiWorld to handle multi-world please tell Slot Machine developper`
https://www.spigotmc.org/resources/myworlds.39594/

**Comment by Klemms** [comment]
No longer necessary due to plugin changes
