### ISSUE TITLE
Vote Points not spending on slot machine rolls. Infinite bug.

### ISSUE THREAD

**Issue by Wolvend** [Klemms/SlotMachineIssues#25]
We're having issues with our slot machine spending Vote Points. No matter how much bugtesting and debugging. There is no reason this should be happening. It spends tokens, money, experience levels. It is extremely intermittent and won't roll correctly. Could you please help us figure this out? We can't have our vote points being easily duped.

Screenshot of proof below
![DFE](https://user-images.githubusercontent.com/69109386/156323522-cd22b026-bd52-49e5-8b07-d16b6105eaff.PNG)

**Comment by Klemms** [comment]
Hi, I'm gonna be investigating that today

**Comment by Klemms** [comment]
I can't reproduce this issue, can you contact me on Discord, Clement#4242
