### ISSUE TITLE
ConnectException

### ISSUE THREAD

**Issue by flashpaul** [Klemms/SlotMachineIssues#29]
I have this warning that keeps reoccurring in console. How can I solve it?

[Server] WARN java.net.ConnectException: Connection timed out
[Server] WARN at java.base/sun.nio.ch.Net.connect0(Native Method)
[Server] WARN at java.base/sun.nio.ch.Net.connect(Net.java:579)
[Server] WARN at java.base/sun.nio.ch.Net.connect(Net.java:568)
[Server] WARN at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[Server] WARN at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[Server] WARN at java.base/java.net.Socket.connect(Socket.java:633)
[Server] WARN at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299)
[Server] WARN at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174)
[Server] WARN at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[Server] WARN at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[Server] WARN at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[Server] WARN at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266)
[Server] WARN at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380)
[Server] WARN at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189)
[Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[Server] WARN at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175)
[Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[Server] WARN at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[Server] WARN at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[Server] WARN at java.base/java.net.URL.openStream(URL.java:1161)
[Server] WARN at slotmachine-6.5.9-SPIGOT.jar//fr.klemms.slotmachine.libs.apache.commons.io.IOUtils.toString(IOUtils.java:2953)
[Server] WARN at slotmachine-6.5.9-SPIGOT.jar//fr.klemms.slotmachine.KlemmsUpdate$1.run(KlemmsUpdate.java:76)
[Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[Server] WARN at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
[Server] WARN at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[Server] WARN at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Klemms** [comment]
Should be fixed
