### ISSUE TITLE
console errors and warnings

### ISSUE THREAD

**Issue by PystoyPlayer** [Klemms/SlotMachineIssues#30]
On stopping: https://pb.superhub.xyz/c8PDXc?fmt=raw

**Comment by Klemms** [comment]
Hi, thanks for reporting this, I'm aware of this issue but it is of very low importance so I don't want to make an update just to fix this. I see you're using 2 of my plugins :)

**Comment by PystoyPlayer** [comment]
> Hi, thanks for reporting this, I'm aware of this issue but it is of very low importance so I don't want to make an update just to fix this. I see you're using 2 of my plugins :)

=)

**Comment by PystoyPlayer** [comment]
on active server https://pb.superhub.xyz/XfDwMc?fmt=raw

**Comment by Klemms** [comment]
You can turn off update checks in the KlemmsUpdate folder in your plugins folder, looks like your server cant reach update servers

**Comment by PystoyPlayer** [comment]
> You can turn off update checks in the KlemmsUpdate folder in your plugins folder, looks like your server cant reach update servers

oh, I see. Thanks)
