### ISSUE TITLE
Issue updating.

### ISSUE THREAD

**Issue by KaiserKrister** [Klemms/SlotMachineIssues#33]
Suddenly this error appeared in my chat, i think its an issue with the auto updater? 
what do you think.
https://mclo.gs/HQ7ByxH

**Comment by Klemms** [comment]
Hi, this issue should now be solved

**Comment by KaiserKrister** [comment]
Srry for reopening, was this caused by ssl certificate on your website expiring so the updater didnt allow it?

Im not judging or complaining, just checking nothing bad happend to my server.

**Comment by Klemms** [comment]
Yes it's on my end, the renewal script didn't properly run on my server

**Comment by KaiserKrister** [comment]
Gotcha!
Thank you :)
