### ISSUE TITLE
not giving proper amount of prizes

### ISSUE THREAD

**Issue by melaniebeedot** [Klemms/SlotMachineIssues#34]
for the past week or so, my players have started reporting some of our slot machines sometimes not dispensing the same quantity of prize as shown on the GUI. for example, in the screenshot i've enclosed, 64 coal was the prize they landed on but they only received 6. i thought it might be because i recently upgraded us to slot machine's latest release (even though our server is still on paper 1.19.4) so i tried downgrading again to the previous release, but the problem still persists.

![slots1](https://github.com/Klemms/SlotMachineIssues/assets/98659383/11592b22-6883-4135-9d98-f3d8c68d62bb)

**Comment by Klemms** [comment]
Hi, thanks for the report, can you provide me with your machine file ? And if possible the logs for when this happens

**Comment by melaniebeedot** [comment]
Here's our Slot Machine folder from the server files, but the console logs don't seem to pick up anything at all when the slot machine is spun?

[11:04:10] [Server thread/INFO]: melaniebeedot issued server command: /warp slots
[11:04:13] [Server thread/INFO]: melaniebeedot issued server command: /givetokens melaniebeedot 64
[11:04:18] [Async Chat Thread - #8/INFO]: [Admin] melaniebeedotâ† >> starting
[11:06:52] [Async Chat Thread - #10/INFO]: [Admin] melaniebeedotâ† >> ok 18 tokens spun


[SlotMachine.zip](https://github.com/Klemms/SlotMachineIssues/files/11957091/SlotMachine.zip)

**Comment by Klemms** [comment]
Can you add me on discord : _clement I found the reason why :)

**Comment by dcsepy01** [comment]
same problem

**Comment by Klemms** [comment]
Hi Dominik, I'm having issues reproducing this, but I have made some tests versions to try to fix this, could you contact me on Discord  ?

My discord name is _clement

**Comment by dcsepy01** [comment]
Waiting for response :D My username is krumpli_

**Comment by Klemms** [comment]
Can't send you a friend request, check your discord privacy settings to allow me to send you a request

**Comment by dcsepy01** [comment]
> Can't send you a friend request, check your discord privacy settings to allow me to send you a request

Done
