### ISSUE TITLE
SlotMachines comits sudoku on server restart

### ISSUE THREAD

**Issue by 5KFubi** [Klemms/SlotMachineIssues#41]
I get this error whenever i start the server and no slot machine would work, but magically repairs itself when i do /smreload

29.09 02:18:47 [Server] [INFO] [SlotMachine] Loading file 3ff37aef-e553-4094-8d15-c380bc827139.yml
29.09 02:18:47 [Server] [WARN] java.lang.NullPointerException: Cannot invoke "org.bukkit.World.getBlockAt(int, int, int)" because the return value of "org.bukkit.Bukkit.getWorld(java.util.UUID)" is null
29.09 02:18:47 [Server] [WARN] at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.SlotMachineBlock.getBlock(SlotMachineBlock.java:99)
29.09 02:18:47 [Server] [WARN] at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.SlotMachineBlock.addSlotMachineBlock(SlotMachineBlock.java:27)
29.09 02:18:47 [Server] [WARN] at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.Config.loadMachines(Config.java:467)
29.09 02:18:47 [Server] [WARN] at slotmachine-6.6.0-SPIGOT.jar//fr.klemms.slotmachine.SlotPlugin.onEnable(SlotPlugin.java:120)
29.09 02:18:47 [Server] [WARN] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
29.09 02:18:47 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
29.09 02:18:47 [Server] [WARN] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
29.09 02:18:47 [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
29.09 02:18:47 [Server] [WARN] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640)
29.09 02:18:47 [Server] [WARN] at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551)
29.09 02:18:47 [Server] [WARN] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
29.09 02:18:47 [Server] [WARN] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
29.09 02:18:47 [Server] [WARN] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
29.09 02:18:47 [Server] [WARN] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
29.09 02:18:47 [Server] [WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
29.09 02:18:47 [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Klemms** [comment]
FIxed with next version
