### ISSUE TITLE
Still getting item

### ISSUE THREAD

**Issue by anemul** [Klemms/SlotMachineIssues#5]
So I followed the link to give money and use commands on the plugin page . It works of course , however I am still receiving the item . How do I stop this ? I just want players to win money or lose on this slot machine .

**Comment by kassadGLA** [comment]
I would like to take a look at your slot machine config.

**Comment by Klemms** [comment]
Can you send me your machine's file ?

**Comment by anemul** [comment]
[87ec1267-3b64-42ef-98a6-98af1eb8ffd6.zip](https://github.com/Klemms/SlotMachineIssues/files/3774904/87ec1267-3b64-42ef-98a6-98af1eb8ffd6.zip)
