### ISSUE TITLE
Players can take out items

### ISSUE THREAD

**Issue by JezWalmsley** [Klemms/SlotMachineIssues#8]
If you shift click on a item it will drag it into the player inventory not taking it back out.

**Comment by Klemms** [comment]
I've never been able to reproduce that, either you're using a very old version that became bugged or you're using a different server software than Spigot or PaperSpigot or another plugin is interfering

**Comment by JezWalmsley** [comment]
Im on paper 1.16.1 and no plugins are interfering i can send a video if you want
